### ISSUE TITLE
Provide a method to change the default registry as the original OperatorFilterer also supports this now.

### ISSUE THREAD

**Issue by nidhhoggr** [Vectorized/closedsea#20]
https://github.com/ProjectOpenSea/operator-filter-registry/issues/42

**Comment by Vectorized** [comment]
Hmm, 2100 extra gas.

I do agree with @dievardump on the thread there.

If you do know any projects who will use closedsea and need the registry to be configurable, let me know. May consider if the demand is strong enough.

**Comment by nidhhoggr** [comment]
Okay, so the general consensus is:
1) Way to much gas to remove `constant`
2) No practical purpose in doing this

I'll go ahead and close the issue. Feel free to resurrect if need be. Nice library btw.
